spring:
  application.name: foo-svc
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%{X-B3-TraceId}o" "%r" %s %b %D '
      # pattern: '%h %t "%r" %s %b %D "%{Referer}i" "%{User-agent}i" "%{X-B3-TraceId}i"'
      rotate: true
    basedir: .

foo.svc:
  hostname: localhost
bar:
  schema: http
  host: localhost
  port: 8080
  baseURL: /foo
  max-connection: 10

http-client:
  max-connection: 100
  max-connection-per-route: 10
  connection-request-timeout: 50
  connection-timeout: 100
  socket-timeout: 350
  default-keep-alive: 5
  max-idle-time: 30

hystrix.command.default:
  execution.timeout.enabled: false
  execution.isolation.strategy: SEMAPHORE
  requestCache.enabled: false

rest.retry:
  max-attempts: 2
  backoff:
    delay: 100
    multiplier: 2
    max-interval: 30000


bar-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:${bar.port}
    ServerListRefreshInterval: 15000

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
