spring:
  application.name: foo-svc
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      rotate: true
    basedir: .

foo.svc:
  hostname: localhost
bar:
  schema: http
  host: localhost
  port: 8080
  baseURL: /foo
  max-connection: 20

http-client:
  max-total: 100
  default-max-per-route: 20
  connection-request-timeout: 2000
  connection-timeout: 10000
  socket-timeout: 10000
  default-keep-alive: 5
  max-idle-time: 30

