spring:
  application.name: foo-svc
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      rotate: true
    basedir: .

foo.svc:
  hostname: localhost
bar:
  schema: http
  host: localhost
  port: 8080
  baseURL: /foo
  max-connection: 10

http-client:
  max-connection: 100
  max-connection-per-route: 10
  connection-request-timeout: 50
  connection-timeout: 100
  socket-timeout: 350
  default-keep-alive: 5
  max-idle-time: 30

hystrix.command.default:
  execution.isolation.strategy: SEMAPHORE
  requestCache.enabled: false

rest.retry:
  max-attempts: 2
  backoff:
    delay: 100
    multiplier: 2
    max-interval: 30000

