DROP TABLE foo IF EXISTS;
DROP TABLE foo_aud IF EXISTS;
DROP TABLE revinfo IF EXISTS;
CREATE TABLE foo
  (
     id            BIGINT NOT NULL,
     delete_token  VARCHAR(255),
     NAME          VARCHAR(255) NOT NULL,
     version       BIGINT NOT NULL,
     created_date  BIGINT NOT NULL,
     modified_date BIGINT,
     description   VARCHAR(255),
     PRIMARY KEY (id)
  );

CREATE TABLE foo_aud
  (
     id            BIGINT NOT NULL,
     rev           INTEGER NOT NULL,
     revtype       TINYINT,
     delete_token  VARCHAR(255),
     NAME          VARCHAR(255),
     version       BIGINT,
     created_date  BIGINT,
     modified_date BIGINT,
     description   VARCHAR(255),
     PRIMARY KEY (id, rev)
  );

CREATE TABLE revinfo
  (
     rev      INTEGER GENERATED BY DEFAULT AS IDENTITY,
     revtstmp BIGINT,
     PRIMARY KEY (rev)
  );

ALTER TABLE foo
  ADD CONSTRAINT uk_foo_name_deleted_token UNIQUE (NAME, delete_token);

ALTER TABLE foo_aud
  ADD CONSTRAINT fk_rev_revinfo FOREIGN KEY (rev) REFERENCES
  revinfo;